---
- name: Install required packages
  loop:
    - keepalived
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - keepalived

- name: Create script group
  when: keepalived_script_group | default(False) and keepalived_script_group != "root"
  ansible.builtin.group:
    name: "{{ keepalived_script_group }}"
    system: True
    state: present
  tags:
    - keepalived

- name: Create script user
  when: keepalived_script_user | default(False) and keepalived_script_user != "root"
  ansible.builtin.user:
    name: "{{ keepalived_script_user }}"
    group: "{{ keepalived_script_group }}"
    ansible.builtin.shell: "{{ keepalived_script_shell }}"
    system: True
    createhome: False
    state: present
  tags:
    - keepalived

- name: Write tmpfiles config
  ansible.builtin.copy:
    content: "d /var/run/keepalived 0755 {{ keepalived_script_user | default('root') }} {{ keepalived_script_group | default('root') }} -"
    dest: /etc/tmpfiles.d/keepalived.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - keepalived

- name: Create tmpfiles dir
  ansible.builtin.file:
    path: /var/run/keepalived
    owner: "{{ keepalived_script_user | default('root') }}"
    group: "{{ keepalived_script_group | default('root') }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - keepalived

- name: Write config file
  notify:
    - Restart keepalived
  ansible.builtin.template:
    src: config.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - keepalived

- name: Create instance dir
  loop: "{{ keepalived_instances }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.file:
    path: "/etc/keepalived/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - keepalived

- name: Create instance notify
  loop: "{{ keepalived_instances }}"
  loop_control:
    label: "{{ item.name }}"
  ansible.builtin.template:
    src: notify.j2
    dest: "/etc/keepalived/{{ item.name }}/notify.sh"
    owner: "{{ keepalived_script_user | default('root') }}"
    group: "{{ keepalived_script_group | default('root') }}"
    mode: u=rwx,g=rwx,o=
  tags:
    - keepalived

- name: Start keepalived service
  ansible.builtin.systemd:
    name: keepalived
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - keepalived

- name: Include exporter tasks
  when: keepalived_exporter_enabled | default(False)
  ansible.builtin.include_tasks: exporter.yml
  tags:
    - keepalived
    - keepalived-exporter

...
