# Standards: 1.2
---
- name: Install required packages
  loop:
    - keepalived
  package:
    name: "{{ item }}"
    state: present
  tags:
    - keepalived

- name: Create script group
  when: keepalived_script_group | default(False) and keepalived_script_group != "root"
  group:
    name: "{{ keepalived_script_group }}"
    system: True
    state: present
  tags:
    - keepalived

- name: Create script user
  when: keepalived_script_user | default(False) and keepalived_script_user != "root"
  user:
    name: "{{ keepalived_script_user }}"
    group: "{{ keepalived_script_group }}"
    shell: "{{ keepalived_script_shell }}"
    system: True
    createhome: False
    state: present
  tags:
    - keepalived

- name: Write tmpfiles config
  copy:
    content: "d /var/run/keepalived 0755 {{ keepalived_script_user | default('root') }} {{ keepalived_script_group | default('root') }} -"
    dest: /etc/tmpfiles.d/keepalived.conf
  tags:
    - keepalived

- name: Create tmpfiles dir
  file:
    path: /var/run/keepalived
    owner: "{{ keepalived_script_user | default('root') }}"
    group: "{{ keepalived_script_group | default('root') }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - keepalived

- name: Write config file
  notify:
    - Restart keepalived
  template:
    src: config.j2
    dest: /etc/keepalived/keepalived.conf
  tags:
    - keepalived

- name: Create instance dir
  loop: "{{ keepalived_instances }}"
  loop_control:
    label: "{{ item.name }}"
  file:
    path: "/etc/keepalived/{{ item.name }}"
    state: directory
  tags:
    - keepalived

- name: Create instance notify
  loop: "{{ keepalived_instances }}"
  loop_control:
    label: "{{ item.name }}"
  template:
    src: notify.j2
    dest: "/etc/keepalived/{{ item.name }}/notify.sh"
    owner: "{{ keepalived_script_user | default('root') }}"
    group: "{{ keepalived_script_group | default('root') }}"
    mode: u=rwx,g=rwx,o=
  tags:
    - keepalived

- name: Start keepalived service
  systemd:
    name: keepalived
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - keepalived

- name: Include exporter tasks
  when: keepalived_exporter_enabled | default(False)
  include: exporter.yml
  tags:
    - keepalived
    - keepalived-exporter

...
